### ISSUE TITLE
CCS stops working after installing C2000 compiler v6.4

### ISSUE THREAD

**Issue by altendky** [altendky/docker-ccstudio#1]
https://e2e.ti.com/support/development_tools/code_composer_studio/f/81/p/687986/2541405

**Comment by altendky** [comment]
@sirde, any chance you came up with some nifty tools or techniques for debugging CCS when you were making your Docker image?  I'm trying to make one for CCSv8 with the C2000 compiler V6.4 but installing the latter breaks it.  I've documented my efforts thus far in the TI link above.

Thanks for any suggestions you can provide.

**Comment by sirde** [comment]
Hi altendky, 

You can see my discussion with TI on their forum if you have not yet checked it: https://e2e.ti.com/support/development_tools/code_composer_studio/f/81/t/633095?CCS-CCSTUDIO-Trying-to-install-CCS-in-a-docker-container

Basically I used a docker container with VNC to debug using the graphical interface, and then back with the standard ubuntu container I checked the logs (Which are a kind of a mess with location/naming and non-problematic errors....)

Good luck!

**Comment by altendky** [comment]
I finally got back to this in #4 (albeit with new versions).  I'm still working through some issues when used by Jenkins but manually the image is working.  Used xvfb+x11vnc and a dummy `-help` call to allow for the next-startup-after-installation progress dialog.  We're _so_ close to GUI-free...
